# 예외처리
## 프로그램의 오류
* 어떤 원인에 의해 오동작하거나 비정상적으로 종료되는 경우
* 발생시점에 따라 구분이 가능
  * 컴파일 에러
    * 문법이 틀리는 경우
  * 런타임 에러
    * 컴파일 ok, 실행과정에서 문제 발생
  * 논리적 에러
    * 원하는 결과가 아닌 경우
## 에러와 예외
* Error: 발생하면 복구할 수 없는 심각한 오류
* Exception: 프로그래머가 적절한 코드를 통해 대비할 수 있는 오류
## 예외처리
* 예외 발생 시 프로그램의 비정상 종료를 막고 정상적인 실행 상태를 유지하는 것
* 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요
## 예외 클래스의 계층
* 자바에서는 예외도 객체이고 클래스로 되어 있다.
* RunTimeExcption 클래스들 
  * 프로그래머의 실수로 발생하는 계열
  * <u>unchecked exception</u>
  * 대처 코드가 없어도 컴파일 문제 X
* Excption 클래스들
  * 사용자의 실수 등 외적인 요인에 의해 발생하는 계열
  * <u>checked exception</u>
  * 대처 코드가 없으면 컴파일 진행 X
```java
int[] nums = {10};
		
		// UncheckedException
		// = 컴파일 시간에 확인 x -> 빨간 줄 x
		// - 실행 중에 발생
		// - 예외 처리를 강제하지 않음
		// - 예외 처리: try ~ catch를 이용해서 처리를 할 수도 있다.
		System.out.println(nums[2]);
		
		
		// CheckedException
		// - 컴파일 시간에 확인 -> 빨간 줄
		// - 예외 처리를 강제
		// - 에외처리 방법: try ~ catch를 사용해서 직접 처리, throws 선언해서 예외처리 위임(간접처리)
		// Thread.sleep(1000); // 빨간줄은 checked => 컴파일 안됨.
```
## 예외처리 키워드 
* 직접 처리 
  * try
  * catch
  * finally

## 예외처리 (try~catch 구문)
* 프로그램 실행 시 발생할 수 있는 예외에 대한 대비코드 작성
* 비정상적인 종료를 막고, 정상적인 상태를 유지함
* 예외 발생 시 JVM의 에외처리가 받아서 정리
```java
// try ... catch 문을 사용한 예외처리
		
		int[] nums  = {10};
		
		// 1. 예외가 발생했을 때: 1 4 5
		// 2. 예외가 발생했는데 처리하지 못했을 때: 1 (2<-에러) 비정상적 종료
		// 3. 예외가 발생하지 않았을 때?: 1 2 3 5
		
		try {
			//예외가 발생할 수 있는 코드는 try문 안에 넣는다.
			System.out.println("정상코드 1"); //1
			System.out.println(nums[0]); //2
			System.out.println("정상코드 2"); //3
	} catch(ArrayIndexOutOfBoundsException e) { // catch() 예외를 파라미터로 받는다.
		// 예외 대처 코드 작성\
		System.out.println("배열의 인덱스 범위를 벗어났습니다."); //4
	}
		System.out.println("프로그램 종료."); //5
```
```java
try {
    // (1)예외가 발생할 수 있는 코드
    // (2)정상코드    
} catch(Exception e){
    // (3)예외가 발생했을 때 처리할 코드
}
// (4)일반코드
```
## 다중 예외처리
* try 블록에서 여러 종류의 예외가 발생할 경우
* 하나의 try 블록에 여러 개의 catch 블록 추가 가능
```java
// try ... catch 문을 사용한 예외처리
		
		int[] nums  = {10};
		
		// 1. 예외가 발생했을 때: 1 4 5
		// 2. 예외가 발생했는데 처리하지 못했을 때: 1 (2<-에러) 비정상적 종료
		// 3. 예외가 발생하지 않았을 때?: 1 2 3 5
		
		try {
			//예외가 발생할 수 있는 코드는 try문 안에 넣는다.
			System.out.println("정상코드 1"); //1
			System.out.println(nums[2]); //2
			int num = 4 / 0;
			System.out.println("정상코드 2"); //3
	} catch(ArrayIndexOutOfBoundsException | ArithmeticException e) { // catch() 예외를 파라미터로 받는다.
		// 예외 대처 코드 작성\
		System.out.println("배열의 인덱스 범위를 벗어났습니다, 계산 오류가 발생했습니다."); //4
		if(e instanceof ArithmeticException) {
			System.out.println("계산 오류입니다.");
		}
	}
		System.out.println("프로그램 종료."); //5
```
## 다중 예외 처리 유의 사항
* JVM이 던진 예외는 catch 문장을 찾을 때는 다형성이 적용 됨
* 상위 타입의 에외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음
* 상속 관계가 없는 경우는 무관
* 상속 관계에서는 작은 범위(자식)에서 큰 범위(조상)순으로 정의
```java
try{
    // exception이 발생할 만한 코드
}catch (XXException e){
    // XXExceptiond 발생 시 처리 코드
}catch (YYException e){
    // YYExceptiond 발생 시 처리 코드
}catch (Exception e){
    // Exception 발생 시 처리 코드
}
```
## Exception
* getMessage(): 발생된 예외에 대한 구체적인 메시지를 반환
* printStackTrace(): 예외 발생 당시의 호출 스택(Call Stack)을 출력한다.
```java
System.out.println(e.getMessage());
e.setStackTrace();
```
## 메서드에서 예외 던지기
* 메서드 선언부에 throws 키워드를 사용하여 예외 작성
* 예외가 여러 개일 경우, 를 이용하여 나열
* 메서드가 예외를 처리하는 것이 아닌 전달
* 조상 타입의 예외로 처리 가능

## 메서드 재정의와 throws
* 메서드 재정의 시 조상클래스 메서드가 던지는 에외보다 부모 예외를 던질 수 없다.

## finally 구문
* finally는 예외 발생 여부와 상관 없이 언제나 실행 
```java
try {
    // 예외가 발생할 가능성이 있는 코드
}catch(Exception e){
    //예외 처리 코드
}finally{
    // 예외 상관 없이 항상 수행해야 하는 코드
}
```

## 자동 자원 반납 구문(try with resources)
* 자원 등을 반납할 때 finally에서 close()를 통해 반납을 주로 함
* 코드가 지저분해 지고 다른 예외상황을 발생시킬 수 있음
* try() -> 괄호 안에 객체를 생성하는 코드를 작성하면, 해당 객체는 close()를 호출하지 않아도 블록을 벗어 나는 순간 close()가 호출됨.

## 사용자 정의 예외
* 기존에 정의된 예외 이외에 사용자가 직접 정의 예외를 작성할 수 있음
* 대부분 Exception 또는 RuntimeException 클래스를 상속받아 작성
  * checkes exception 활용 : 명시적 에외 처리 또는 throws 필요 (코드는 복잡해지지만 처리, 누락 등 오류 발생 가능성은)
  * runtime exception 활용 : 묵시적 예외 처리 가능 (코드가 갈결해지지지만 예외 처리, 누락 사능성 발생)